### ISSUE TITLE
t->mon shows as 83

### ISSUE THREAD

**Issue by retromuz** [akafugu/ds_rtc_lib#1]
I tried the avr-gcc version of your library. It returns the month as 83 when it actually is 3. Others returns correct values though. When I use another Arduino library (https://github.com/rodan/ds3231) it does not return unusual values though.

**Comment by retromuz** [comment]
In your project the Arduino version also shows month as 83. Please help.

Time: 15-83-31 17:5:53
Temperature: 30.110010C

My code is as below:
WireRtcLib::tm\* t = rtc.getTime();
  Serial.print("Time: ");
  Serial.print(t->year);
  Serial.print("-");
  Serial.print(t->mon);
  Serial.print("-");
  Serial.print(t->mday);
  Serial.print(" ");
  Serial.print(t->hour);
  Serial.print(":");
  Serial.print(t->min);
  Serial.print(":");
  Serial.println(t->sec);

**Comment by retromuz** [comment]
Compared code with another Arduino based library (https://github.com/rodan/ds3231) and found that the century indicator coming inside month value is not taken into consideration. I am now fixing it up. Will push fixed code soon.

**Comment by retromuz** [comment]
Hi there,

I fixed the gcc version with proper century calculation. Please find fixed code at https://github.com/karunadheera/ds_rtc_lib.

Best Regards,
Prageeth

**Comment by perjg** [comment]
Hi,

Thanks for this. If you send a pull request to akafugu/ds_rtc_lib I can
include it in our repository too.

Sincerely,
  Per Johan Groland

On Mon, Apr 6, 2015 at 8:43 AM, Prageeth Karunadheera <
notifications@github.com> wrote:

> Hi there,
> 
> I fixed the gcc version with proper century calculation. Please find fixed
> code at https://github.com/karunadheera/ds_rtc_lib.
> 
> Best Regards,
> Prageeth
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akafugu/ds_rtc_lib/issues/1#issuecomment-89869478.

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by retromuz** [comment]
Hi Johan,

Created a pull request! Have a great week ahead!

Thanks!
Prageeth.

**Comment by perjg** [comment]
Merged! Thanks for the contribution.

On Mon, Apr 6, 2015 at 7:38 PM, Prageeth Karunadheera <
notifications@github.com> wrote:

> Hi Johan,
> 
> Created a pull request! Have a great week ahead!
> 
> Thanks!
> Prageeth.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akafugu/ds_rtc_lib/issues/1#issuecomment-90010286.

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by retromuz** [comment]
You are very welcome! Ill check the Arduno version too because It should also have the same issue I guess. Closing this issue.
